article_module/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.ArticlesListView.as_view(), name='articles_list'),
    path('cat/<str:category>', views.ArticlesListView.as_view(), name='articles_by_category_list'),
    path('<pk>/', views.ArticleDetailView.as_view(), name='articles_detail'),
    path('add-article-comment', views.add_article_comment, name='add_article_comment')
]

djangoProject5/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('home_module.urls')),
    path('', include('account_module.urls')),
    path('articles/', include('article_module.urls')),
    path('contact-us/', include('contact_module.urls')),
    path('products/', include('product_module.urls')),
    path('user/', include('user_panel_module.urls')),
    path('order/', include('order_module.urls')),
    path('admin/', admin.site.urls),
    # path('admin-panel/', include('admin_panel.urls'))
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home_module/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.HomeView.as_view(), name='home_page'),
    path('about-us/', views.AboutUsView.as_view(), name='about_us_page'),
    path('about-us/service/', views.ServiceView, name='services_page'),
    path('about-us/agent/', views.AgentView, name='agent_page')
]

article_module/models.py
from django.db import models
from jalali_date import date2jalali
from ckeditor.fields import RichTextField
from account_module.models import User


class ArticleCategory(models.Model):
    parent = models.ForeignKey('ArticleCategory', null=True, blank=True, on_delete=models.CASCADE,
                               verbose_name='دسته بندی والد')
    title = models.CharField(max_length=200, verbose_name='عنوان دسته بندی')
    url_title = models.CharField(max_length=200, unique=True, verbose_name='عنوان در url')
    is_active = models.BooleanField(default=True, verbose_name='فعال / غیرفعال')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'دسته بندی مقاله'
        verbose_name_plural = 'دسته بندی های مقاله'


class Article(models.Model):
    title = models.CharField(max_length=300, verbose_name='عنوان مقاله')
    slug = models.SlugField(max_length=400, db_index=True, allow_unicode=True, verbose_name='عنوان در url')
    image = models.ImageField(upload_to='images/articles', verbose_name='تصویر مقاله')
    short_description = models.TextField(verbose_name='توضیحات کوتاه')
    text = RichTextField(verbose_name='متن مقاله', null=True, blank=True)
    # text = models.TextField(verbose_name='متن مقاله')
    is_active = models.BooleanField(default=True, verbose_name='فعال / غیرفعال')
    selected_categories = models.ManyToManyField(ArticleCategory, verbose_name='دسته بندی ها')
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='نویسنده', null=True, editable=False)
    create_date = models.DateTimeField(auto_now_add=True, editable=False, verbose_name='تاریخ ثبت')

    def __str__(self):
        return self.title

    def get_jalali_create_date(self):
        return date2jalali(self.create_date)

    def get_jalali_create_time(self):
        return self.create_date.strftime('%H:%M')

    class Meta:
        verbose_name = 'مقاله'
        verbose_name_plural = 'مقالات'


class ArticleComment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, verbose_name='مقاله')
    parent = models.ForeignKey('ArticleComment', null=True, blank=True, on_delete=models.CASCADE, verbose_name='والد')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='کاربر')
    create_date = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')
    text = models.TextField(verbose_name='متن نظر')

    def __str__(self):
        return str(self.user)

    class Meta:
        verbose_name = 'نظر مقاله'
        verbose_name_plural = 'نظرات مقاله'

article_module/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from django.views.generic import DetailView
from django.views.generic.list import ListView
from article_module.models import Article, ArticleCategory, ArticleComment
from site_module.models import SiteBanner


class ArticlesListView(ListView):
    model = Article
    paginate_by = 6
    template_name = 'article_module/articles_page.html'

    def get_context_data(self, *args, **kwargs):
        context = super(ArticlesListView, self).get_context_data(*args, **kwargs)
        context['banner'] = SiteBanner.objects.filter(is_active=True,
                                                      position__iexact=SiteBanner.SiteBannerPositions.product_list)
        return context

    def get_queryset(self):
        query = super(ArticlesListView, self).get_queryset()
        query = query.filter(is_active=True)
        category_name = self.kwargs.get('category')
        if category_name is not None:
            query = query.filter(selected_categories__url_title__iexact=category_name)
        return query


class ArticleDetailView(DetailView):
    model = Article
    template_name = 'article_module/article_detail_page.html'

    def get_queryset(self):
        query = super(ArticleDetailView, self).get_queryset()
        query = query.filter(is_active=True)
        return query

    def get_context_data(self, **kwargs):
        context = super(ArticleDetailView, self).get_context_data()
        article: Article = kwargs.get('object')
        context['comments'] = ArticleComment.objects.filter(article_id=article.id, parent=None).order_by(
            '-create_date').prefetch_related('articlecomment_set')
        context['comments_count'] = ArticleComment.objects.filter(article_id=article.id).count()
        context['banners'] = SiteBanner.objects.filter(is_active=True,
                                                       position__iexact=SiteBanner.SiteBannerPositions.product_list)
        return context


def article_categories_component(request: HttpRequest):
    article_main_categories = ArticleCategory.objects.prefetch_related('articlecategory_set').filter(is_active=True,
                                                                                                     parent_id=None)

    context = {
        'main_categories': article_main_categories
    }
    return render(request, 'article_module/partial/article_categories_partial.html', context)


def add_article_comment(request: HttpRequest):
    if request.user.is_authenticated:
        article_id = request.GET.get('article_id')
        article_comment = request.GET.get('article_comment')
        parent_id = request.GET.get('parent_id')
        # print(article_id, article_comment, parent_id)
        new_comment = ArticleComment(article_id=article_id, text=article_comment, user_id=request.user.id,
                                     parent_id=parent_id)
        new_comment.save()
        context = {
            'comments': ArticleComment.objects.filter(article_id=article_id, parent=None).order_by(
                '-create_date').prefetch_related('articlecomment_set'),
            'comments_count': ArticleComment.objects.filter(article_id=article_id).count()
        }

        return render(request, 'article_module/includes/article_comments_partial.html', context)

    return HttpResponse('response')

article_module/templates/article_module/article_detail_page.html
{% extends 'shared/_layout.html' %}
{% load render_partial %}
{% load poll_extras %}
{% load thumbnail %}


{% block dis %} {{ article.short_description }} {% endblock %}
{% block title %} {{ article.title }} {% endblock %}

{% block content %}
    <!-- Blog Start -->
    <div class="container-fluid py-5">
        <div class="container py-5">
            <div class="row">
                <div class="col-lg-8">
                    <!-- Blog Detail Start -->
                    <div class="pb-3">
                        <div class="blog-item">
                            <div class="position-relative">
                                <img class="img-fluid w-100" src="{{ article.image.url }}" alt="{{ article.title }}">
                            </div>
                        </div>
                        <div class="bg-white mb-3" style="padding: 30px;">
                            <div class="d-flex mb-3">
                            </div>
                            <h2 class="mb-3">{{ article.title }}</h2>
                            <p>{{ article.text|safe }}</p>
                        </div>
                    </div>
                    <!-- Blog Detail End -->

                    <!-- Comment List Start -->
                    <div id="comments_area" class="bg-white" style="padding: 30px; margin-bottom: 30px;">
                        <h4 class="text-uppercase mb-4" style="letter-spacing: 5px;">{{ comments_count }}</h4>
                        {% for comment in comments %}
                            <div class="media">

                                <img src="{{ comment.user.avatar.url }}" alt="Image" class="img-fluid mr-3 mt-1"
                                     style="width: 45px;">
                                <div class="media-body">
                                    <h6><a href="">{{ comment.user }}</a>
                                        <small><i>{{ comment.create_date | time }}---</i></small><small><i>{{ comment.create_date|show_jalali_date }}</i></small>
                                    </h6>
                                    <p>{{ comment.text }}</p>
                                    <button class="btn btn-sm btn-outline-primary"
                                            onclick="fillParentId({{ comment.id }})">
                                        پاسخ
                                    </button>
                                    {#                                    ----------------------------------- 2div#}

                                </div>
                            </div>

                            {% for sub_comment in comment.articlecomment_set.all %}
                                <div class="media mt-4" style="color: #5bc0de">
                                    <img src="{{ sub_comment.user.avatar.url }}" alt="Image"
                                         class="img-fluid mr-3 mt-1"
                                         style="width: 45px;">
                                    <div class="media-body">
                                        <h6><a href="">{{ sub_comment.user }}</a>
                                            <small><i>{{ sub_comment.create_date | time }}</i></small><small><i>{{ sub_comment.create_date|show_jalali_date }}</i></small>
                                        </h6>
                                        <p style="color: #5bc0de"> {{ sub_comment.text }}</p>
                                        <button class="btn btn-sm btn-outline-primary">پاسخ</button>
                                    </div>
                                </div>
                            {% endfor %}
                        {% endfor %}
                    </div>
                    <!-- Comment List End -->

                    <!-- Comment Form Start -->
                    <div class="bg-white mb-3" style="padding: 30px;">
                        <h4 class="text-uppercase mb-4" style="letter-spacing: 5px;">ارسال نظر</h4>

                        <input type="hidden" id="parent_id" value="">
                        <div class="form-group">
                            <label for="message">پیام *</label>
                            <textarea id="message" cols="30" rows="5" class="form-control"></textarea>
                        </div>
                        <div class="form-group mb-0">
                            <input type="submit" value="ارسال نظر"
                                   class="btn btn-primary font-weight-semi-bold py-2 px-3"
                                   onclick="sendArticleComment({{ article.id }})">
                        </div>
                    </div>
                    <!-- Comment Form End -->
                </div>


                <div class="col-lg-4 mt-5 mt-lg-0">
                    <!-- Author Bio -->
                    <div class="d-flex flex-column text-center bg-white mb-5 py-5 px-4">
                        {% render_partial 'article_module.views.article_categories_component' %}
                        <div class="d-flex justify-content-center">
                        </div>
                    </div>

                    <!-- Search Form -->
                    <div class="mb-5">
                        <div class="bg-white" style="padding: 30px;">
                            <div class="input-group">
                                <div class="carousel-inner">


                                    {% for banner in banners %}
                                        <a href="{{ banner.url }}">
                                            <img src="{{ banner.image.url }}" alt="{{ banner.title }}" id="banner">
                                        </a>
                                    {% endfor %}
                                    <br>
                                    <br>


                                </div>
                            </div>
                        </div>
                    </div>


                    <!-- Recent Post -->
                    <div class="mb-5">
                        <h4 class="text-uppercase mb-4" style="letter-spacing: 5px;">Recent Post</h4>
                        <a class="d-flex align-items-center text-decoration-none bg-white mb-3" href="">

                            <div class="pl-3">
                                <h6 class="m-1 text-center">نویسنده : فورنیکو</h6>
                                <small>{{ article.get_jalali_create_date }}</small>
                            </div>
                        </a>
                    </div>


                </div>
            </div>
        </div>
    </div>
    <!-- Blog End -->

{% endblock %}

article_module/templates/article_module/articles_page.html
{% extends 'shared/_layout.html' %}
{% load thumbnail %}
{% load render_partial %}

{% block title %}لیست محصولات{% endblock %}

{% block content %}
    <!-- Header Start -->
    <div class="container-fluid page-header">
        <div class="container">
            <div class="d-flex flex-column align-items-center justify-content-center" style="min-height: 400px">
                <h3 class="display-4 text-white text-uppercase">Packages</h3>
                <div class="d-inline-flex text-white">
                    <p class="m-0 text-uppercase"><a class="text-white" href="">Home</a></p>
                    <i class="fa fa-angle-double-right pt-1 px-3"></i>
                    <p class="m-0 text-uppercase">Packages</p>
                </div>
            </div>
        </div>
    </div>
    <!-- Header End -->

    <!-- Packages Start -->
    <div class="col-md-12">
        <div class="container-fluid py-5">
            <div class="container pt-5 pb-3">
                <div class="text-center mb-3 pb-3">
                    <h6 class="text-primary text-uppercase" style="letter-spacing: 5px;">وبلاگ</h6>
                    <h1>مقالات</h1>
                </div>
                <div class="row">
                    {% for article in article_list %}
                        {% include 'article_module/includes/article_list_partial.html' with article=article col_size=4 %}
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    <!-- Packages End -->
{% endblock %}